
spring:
 servlet:
  multipart:
   enabled: true
   max-file-size: 500MB
   max-request-size: 100MB
 main:
  allow-circular-references: true
  
 application:
   name: producer-prod

eureka:
 instane: localhost  
