
spring:
 servlet:
  multipart:
   enabled: true
   max-file-size: 500MB
   max-request-size: 100MB
 main:
  allow-circular-references: true

spring:
 jpa:
  hibernate:
   ddl-auto: update
 generate-ddl: true  
 hibernate.ddl-auto: none
 properties:
  hibernate: 
   dialect: org.hibernate.dialect.MySQLDialect
 datasource:
  url: jdbc:mysql://localhost:3306/upgrade_db?useSSL=false 
  username: root
  password: MYSQLtukki67@
  driver-class-name: com.mysql.cj.jdbc.Driver